dist: trusty
sudo: false
language: php
#php:
#- '5.5'
#services:
#- mysql
#install:
#- mysql -e 'CREATE DATABASE aurora;'
#- composer install
#- npm install -g newman
script:
#- php ./travis.php
#- chmod +x ./build.sh
#- "./build.sh"
- zip -r package.zip composer.json
#deploy:
#  skip_cleanup: true
env:
  global:
  - secure: JKhCq2psLnho8G0JPNJSpLb2xN4g6oUa7J7KZBzS5LPLhYPiueFDWdMYqUvYRyZYZHFpBhVhvifqy/eG5MxvdYCqt3/8fLx/AdQM7T9oWsSe9l30MjNmCa4ACuwgSSvcHulVJDMUG6CS5mOfWYfSGV4RoECgpUv6exWmFXDYBZRKrwVEcoZA78YeXJFWGB5f5up7+jqyR83oKIiJzZen5ExMx23eFDa10I0J0ptX5ArkikecmCYqzbveDebv3hP1G7yM9qST0eEycFIBEwsN6jnUvLF4TzND4MKvdc6CjQcm8laJUsKO6iWnyEVUIT6ltyFf4tyRfeVQ0dMVFF57hHG5AJkWjpr8lLf4u/eVYWDSS1iL9h/ntPgThUqFQJfCjGG9N8kzv2faufq1N6gOruoIlyaerYxpZ0H/bqJsTZ3WQKcIh5Z7MiVvNJhEJQt+tM38YY9mV0aV+bm9a/RgGWcfb0Wn/4Gz/rE0ojqdoNKjz+CoiiCo7Db1SdotVT4X5LlXai5wiKqA1Iv6jpQEFXKaKLM4yXbPyoDxAqHSGM6+nptouxKbqx6m4IWgCSNsgYnZpG+0a+eElS5QgYKEogqsHyftMVkG0QvQPWmQ7GMaT09bzGYODdKrARPlgyXUCuS/n2K6p6UyUjBsm9EkF1KnPBkJvKlUb043ZsG9Ors=
  - secure: iHxR2JQC7/V1pfsWZWWJP8j6je02RD9VG39gGY+McD0EXzt6ySdl/G8i5JpRUO0EQDxvy7jFc3y695ctJGKkhf103Qz9UiFtN0D16zJCJuW+tsmA1AP7Gye/VJeeJj4IEGc8HMDp1TqKREjKaTQAVpjgV5oS4smYgPrdpDT3SUv5IQMwFT9EH0UeMzy9HMsQgNoUFbBXWW+Fg2yQ+vM0M+1Zqu/6wdvKfLVZZk0/HlO52rWMPe18k920Zs7PBqsTkJj9QaryvF6750OsNCBoeFkdfmzbj7UAAy5UsO/47KKTcovkmUn85rl7vdBQd4O9SfgMxn09zpkYV++wSI45uJh1OXPcGDFnv88Nht4B89Fo91XnF4psZQoebPRgoEoQCybR9SsHRc39s10dwEJXA4Jv3ZTgBxKMhPfPtu4NXU3DwvwXvOJv36sNDKsQXvfsJHDqBNYHO+w87ah1TskpBif+hjV8uJyyRA4ahdbROTagSK6dfUkmgcGZjb+uWmXbSJrk1zosktqRUBqMYih/Zjk5hcv+t5PXgEfdY+6mdnPZW1ukWVc8g6o9WXETPz4P0PSc8e+BUpI6tPyp45jQtPYpNlRQCZ4ij3wTQCNGGQaeY4bjBmh/tdw9qH/xd3ZZyeGkvC7820CqfGL2G+QXZPbADl5d4ebY7IIwyB1wKQM=
after_success: curl --ftp-create-dirs -T package.zip -u $FTP_USER:$FTP_PASSWORD
  ftp://afterlogic.com/
